CREATE TABLE `leads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`firstName` varchar(128) NOT NULL,
	`lastName` varchar(128) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(32) NOT NULL,
	`address` text,
	`ownershipType` enum('homeowner','renter') NOT NULL,
	`monthlyBillRange` varchar(64),
	`interestType` enum('lease','purchase','battery','all') NOT NULL,
	`billFileKey` text,
	`billFileUrl` text,
	`billFileName` varchar(256),
	`status` enum('New','Contacted','Quoted','Closed','Lost') NOT NULL DEFAULT 'New',
	`source` enum('homepage','financing','about','quote-page','upload-bill','other') NOT NULL DEFAULT 'homepage',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leads_id` PRIMARY KEY(`id`)
);
