export const CITY_LINKS = [
  { name: "Anaheim", href: "/solar/anaheim-ca" },
  { name: "Azusa", href: "/solar/azusa-ca" },
  { name: "Bakersfield", href: "/solar/bakersfield-ca" },
  { name: "Baldwin Park", href: "/solar/baldwin-park-ca" },
  { name: "Bloomington", href: "/solar/bloomington-ca" },
  { name: "Brea", href: "/solar/brea-ca" },
  { name: "Burbank", href: "/solar/burbank-ca" },
  { name: "Chino", href: "/solar/chino-ca" },
  { name: "Chino Hills", href: "/solar/chino-hills-ca" },
  { name: "Claremont", href: "/solar/claremont-ca" },
  { name: "Colton", href: "/solar/colton-ca" },
  { name: "Corona", href: "/solar/corona-ca" },
  { name: "Covina", href: "/solar/covina-ca" },
  { name: "Diamond Bar", href: "/solar/diamond-bar-ca" },
  { name: "Eastvale", href: "/solar/eastvale-ca" },
  { name: "El Monte", href: "/solar/el-monte-ca" },
  { name: "Fontana", href: "/solar/fontana-ca" },
  { name: "Fresno", href: "/solar/fresno-ca" },
  { name: "Fullerton", href: "/solar/fullerton-ca" },
  { name: "Garden Grove", href: "/solar/garden-grove-ca" },
  { name: "Glendora", href: "/solar/glendora-ca" },
  { name: "Grand Terrace", href: "/solar/grand-terrace-ca" },
  { name: "Hacienda Heights", href: "/solar/hacienda-heights-ca" },
  { name: "Highland", href: "/solar/highland-ca" },
  { name: "Inland Empire", href: "/solar/inland-empire-ca" },
  { name: "Irvine", href: "/solar/irvine-ca" },
  { name: "Jurupa Valley", href: "/solar/jurupa-valley-ca" },
  { name: "La Habra", href: "/solar/la-habra-ca" },
  { name: "La Verne", href: "/solar/la-verne-ca" },
  { name: "Lakewood", href: "/solar/lakewood-ca" },
  { name: "Lancaster", href: "/solar/lancaster-ca" },
  { name: "Loma Linda", href: "/solar/loma-linda-ca" },
  { name: "Long Beach", href: "/solar/long-beach-ca" },
  { name: "Los Angeles", href: "/solar/los-angeles-ca" },
  { name: "Montclair", href: "/solar/montclair-ca" },
  { name: "Moreno Valley", href: "/solar/moreno-valley-ca" },
  { name: "Murrieta", href: "/solar/murrieta-ca" },
  { name: "Norco", href: "/solar/norco-ca" },
  { name: "Ontario", href: "/solar/ontario-ca" },
  { name: "Orange", href: "/solar/orange-ca" },
  { name: "Palmdale", href: "/solar/palmdale-ca" },
  { name: "Pomona", href: "/solar/pomona-ca" },
  { name: "Rancho Cucamonga", href: "/solar/rancho-cucamonga-ca" },
  { name: "Redlands", href: "/solar/redlands-ca" },
  { name: "Rialto", href: "/solar/rialto-ca" },
  { name: "Riverside", href: "/solar/riverside-ca" },
  { name: "San Bernardino", href: "/solar/san-bernardino-ca" },
  { name: "San Dimas", href: "/solar/san-dimas-ca" },
  { name: "Santa Ana", href: "/solar/santa-ana-ca" },
  { name: "Temecula", href: "/solar/temecula-ca" },
  { name: "Thousand Oaks", href: "/solar/thousand-oaks-ca" },
  { name: "Torrance", href: "/solar/torrance-ca" },
  { name: "Upland", href: "/solar/upland-ca" },
  { name: "Ventura", href: "/solar/ventura-ca" },
  { name: "Walnut", href: "/solar/walnut-ca" },
  { name: "West Covina", href: "/solar/west-covina-ca" },
] as const;
